### ISSUE TITLE
[APP REQUEST] qBittorrent

### ISSUE THREAD

**Issue by ClementNerma** [meienberger/runtipi-appstore#64] opened 2022-10-12 08:49 UTC
qBittorrent is a famous open-source torrent client that also has a WebUI for managing the torrents.

Link to the website: https://www.qbittorrent.org/

**Comment by meienberger** [comment] 2022-10-12 20:16
Hello thanks for your suggestion, I'm closing this request as it is a duplicate of #27. qBittorrent is the next app I'll add

**Closed by meienberger** 2022-10-12 20:16 UTC
